export const RECIPIES_LOADED_ERROR = "RECIPIES_LOADED_ERROR";
export const RECIPIES_LOADED_SUCCESS = "RECIPIES_LOADED_SUCCESS";

export const NUTRITIONS_LOADED_ERROR = "NUTRITIONS_LOADED_ERROR";
export const NUTRITIONS_LOADED_SUCCESS = "NUTRITIONS_LOADED_SUCCESS";

// Home page actions - featured recipes
export const FEATURED_LOADED_ERROR = "FEATURED_LOADED_ERROR";
export const FEATURED_LOADED_SUCCESS = "FEATURED_LOADED_SUCCESS";